# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myRealmSpace' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift', '3.13.1'
  # Pods for myRealmSpace

end
